import Header from "@/components/Header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '../styles/global.scss'
import '../styles/reset.scss'
import Document, { Html, Head, Main, NextScript } from 'next/document';
import MainIcon from '@/components/img/svg/MainIcon.svg'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ataba",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        
        {children}</body>
    </html>
  );
}
